### ISSUE TITLE
Enhancements: Custom Cell Rendering/Retention Charts

### ISSUE THREAD

**Issue by gryevns** [arunghosh/react-heatmap-grid#10]
Hey, couple of suggestions/enhancements - want to know your thoughts before raising any PRs...

1. Custom Cell Render

It would be ncie to render something other than `&nbsp;` within cells, e.g. the value with unit.

```
<HeatMap render={value => `${value}%`} />
```

2. Background Opacity

Currently setting the background & opacity means any textual value (e.g. above) inherits the opacity - instead it would be nice to use rgba - this means converting from hex to rgba to maintain backwards compatibility.

3. Retention Chart Support

The current gradient implementation works on a min/max across the whole dataset, whereas, for a retention chart the first value of each row is the "base" and the subsequent row values have a gradient compared to this value.

```
<HeatMap type="retention" />
```

![screen shot 2018-09-17 at 20 40 59](https://user-images.githubusercontent.com/7195374/45646005-0d064c00-baba-11e8-8c4e-d6d42960fe9b.png)

**Comment by arunghosh** [comment]
@gryevns The above 3 features looks good. I happy to have the pull request for these features. Thank you :)
