### ISSUE TITLE
Cell positions offset when using a small height

### ISSUE THREAD

**Issue by d-beltran** [arunghosh/react-heatmap-grid#170]
Hi :)

I may have found a bug. When the 'height' parameter is small (e.g. 5) cell rows with y label are displayed separated by a white space (see the figure below)

![Captura de pantalla de 2020-05-19 14-03-47](https://user-images.githubusercontent.com/44979434/82324242-9d0c3f80-99d9-11ea-9918-9af5f63f68a3.png)
![Captura de pantalla de 2020-05-19 13-51-06](https://user-images.githubusercontent.com/44979434/82323174-f2dfe800-99d7-11ea-8c08-d839f7fecb9b.png)

I tried to fix this with other parameters but I didn't succeed.

However there is a small change in the code which seems to fix this. I have not deep checked if this modification has side effects, but it may be useful.

In the 'DataGrid.jsx' script:
![Captura de pantalla de 2020-05-19 13-58-18](https://user-images.githubusercontent.com/44979434/82323764-d1333080-99d8-11ea-89df-294f2cfd014f.png)
![Captura de pantalla de 2020-05-19 14-01-11](https://user-images.githubusercontent.com/44979434/82324015-39821200-99d9-11ea-8a38-0b8d28379599.png)

I am new in GitHub, so I apologize if this is not the correct way to suggest changes. If there is a 'suggest commit' protocol please point me how to do it and I will.

Cheers

**Comment by arunghosh** [comment]
@d-beltran Thank you very for conveying the issue and the fix. This is fixed in version `v0.8.2`.
