### ISSUE TITLE
Making column values inactive in heatmap

### ISSUE THREAD

**Issue by therealarcher** [arunghosh/react-heatmap-grid#182]
Hello,

Thank you for creating this tool!  I'm wondering whether one can apply the heatmap only to selected columns.  For example in a table with 6 columns, no heatmap applied for the first 2 columns (ie maybe a white background, regardless of the value in the column), and the heatmap colors applied to the next 4 columns.

Thanks in advance!

**Comment by arunghosh** [comment]
@therealarcher If I understood you correctly, you can use `cellStyle` or `cellRender` for your purpose. If it doesn't work, let me know. 

```
    cellStyle={(background, value, min, max, data, x, y) => ({
      background: `rgba(66, 86, 244, ${1 - (max - value) / (max - min)})`,
      fontSize: "11px",
    })}
    cellRender={value => value && `${value}%`}
```

**Comment by therealarcher** [comment]
Thank you for the response.  Yes, Eventually I was able to make it work using the x,y parameters.
