### ISSUE TITLE
yLables colliding with the data when bigger in length 

### ISSUE THREAD

**Issue by monikadixit** [arunghosh/react-heatmap-grid#210]
![image](https://user-images.githubusercontent.com/19951102/98642358-5cbbc780-2353-11eb-8f3e-d687ed261304.png)

**Comment by arunghosh** [comment]
@monikadixit There is a new package available - https://github.com/arunghosh/react-grid-heatmap

Can you check that?

**Comment by monikadixit** [comment]
Thanks Arun for replying,  I want to use value while rendering cell
style.Basically have the cell color on the basis of value. However it is
not accessing the value correctly.

cellStyle={(_x, _y, ratio, *value*) => ({
background: setRGB(value),
fontSize: ".7rem",
color: `rgb(0, 0, 0, ${ratio / 2 + 0.4})`
})}

**Comment by arunghosh** [comment]
@monikadixit 

The value parameter is not there in the `cellStyle`. But you can get it using `x`, `y`.

```
cellStyle={(x, y, ratio) => ({
  background: setRGB(data[x][y]),
  fontSize: ".7rem",
  color: `rgb(0, 0, 0, ${ratio / 2 + 0.4})`
})}
```

Can you check if this works?
