### ISSUE TITLE
yLables colliding with data when data becomes scrollable 

### ISSUE THREAD

**Issue by monikadixit** [arunghosh/react-heatmap-grid#211]
![image](https://user-images.githubusercontent.com/19951102/98642831-14e97000-2354-11eb-9a88-ee8ec66626b3.png)
When it is scrolled 

![image](https://user-images.githubusercontent.com/19951102/98642965-4f530d00-2354-11eb-80ca-251935f77db2.png)

**Comment by arunghosh** [comment]
@monikadixit There is a new package available - https://github.com/arunghosh/react-grid-heatmap

Can you check that?
