### ISSUE TITLE
Is there any way to select multiple DataGrids ?

### ISSUE THREAD

**Issue by Saroopashree** [arunghosh/react-heatmap-grid#212]
I see that DataGrids have an onClick callback which is really useful.
But I need to select multiple DataGrids that are adjacent either horizontally or vertically as you would do in a spreadsheet. Mouse down on the first DataGrid and slide all the way to the ending DataGrid and then release the mouse.

Is this possible ?

**Comment by arunghosh** [comment]
Sorry. Currently this is not supported.

But I think you fork the code and achieve it using mouse events.

**Comment by Saroopashree** [comment]
Thanks @arunghosh !! 🙂
