### ISSUE TITLE
A responsive problem I tried to correct it, but it wouldn't let me. Could you kindly assist me?

### ISSUE THREAD

**Issue by zeeshan010101** [arunghosh/react-heatmap-grid#231]
As you can see, I created a box with bootstrap col-auto col-md-8 m-auto, however when I reduced the screen size to test responsiveness, they went outside. @arunghosh 
![Screenshot 2021-10-15 142927](https://user-images.githubusercontent.com/92445751/137465714-1231bec1-2d9a-40df-8c3f-c1e5bd039403.png)

**Comment by arunghosh** [comment]
Can you check https://github.com/arunghosh/react-grid-heatmap/ ?

This handled responsiveness better. It has a similar interface.
