### ISSUE TITLE
Question: Changing hover value

### ISSUE THREAD

**Issue by chookie** [arunghosh/react-heatmap-grid#64]
This component is great thank you.  Working perfectly so far.  Just wondering whether it would be possible to change the hover text, perhaps using a function like cellRender.  I am using an object as a value so I can use it for the click event but this means the hover text shows as [object, object].

**Comment by arunghosh** [comment]
@chookie Sorry for the late reply. 

Currently not supported.  But it is possible. 

To confirm, you need a prop via which you can render individual cells?

**Comment by MutatedGamer** [comment]
I was also wondering if it's possible to do this. What do you mean "it is possible," can you provide instructions how to do this?

**Comment by arunghosh** [comment]
@MutatedGamer This feature was added via [this commit ](https://github.com/arunghosh/react-heatmap-grid/pull/76/files). It is also mentioned in the Readme. It is done via `title` property which takes a function. Using the function you can format the title(hover) as required.
