### ISSUE TITLE
example does not render in safari because of typo in rgb vs rgba

### ISSUE THREAD

**Issue by perbergland** [arunghosh/react-heatmap-grid#86]
Took me a while to figure out what was happening here :)

Change this in the readme:

```
background: `rgb(66, 86, 244, ${1 - (max - value) / (max - min)})`,
```

to 
```
background: `rgba(66, 86, 244, ${1 - (max - value) / (max - min)})`,
```

otherwise it won't render in safari which is strict about this

**Comment by arunghosh** [comment]
@perbergland 

Sorry for that. 

Thank you for reporting :)

I have updated the readme.
