### ISSUE TITLE
How to show on xLabels in title

### ISSUE THREAD

**Issue by raguct25** [arunghosh/react-heatmap-grid#94]
**How to get xLabels with title**
xLabels=[first,second,third,four,five]

**title**={(value) => `${value}°C`}

The **title** is shows values . **23°C**

How to show xLabel with title.  **first - 23°C**

Whenever the cursor point the cell i want to show this toolip : **first - 23°C**

**Comment by arunghosh** [comment]
@raguct25 You can do this using the `title` property as shown below. For details check the [demo](https://codesandbox.io/s/n1kj4n6po4) code.

```
title={(value, unit, index) => value && `${value}% - ${xLabels[index]}`}
```
